repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-ast
      - id: debug-statements

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.6'
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.0'
    hooks:
      - id: mypy
        additional_dependencies: [types-requests==2.31.0.10]
